#! /bin/bash

#Program: x-html
#Usage: x-html filename.html

FILENAME="$1"
X_SIZE=1024

DATE="$(date)"
CONTENT_SIZE=$(stat -c "%s" $FILENAME)

if [[ ${CONTENT_SIZE} -lt ${X_SIZE} ]] ; then
  HTML_TYPE="text/html"
else
  HTML_TYPE="application/x-html"
fi

echo HTTP/1.1 200 OK
echo Server: premortal/cit-384/${USER}
echo Date: ${DATE}
echo Content-Type: ${HTML_TYPE}
echo Content-Length: ${CONTENT_SIZE}
echo ""

if (( CONTENT_SIZE < X_SIZE )) ; then
  cat ${FILENAME}
else
  cat ${FILENAME} | compress - | base64
fi
